apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
spec:
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: netflow/staging/backend
        property: DB_PASSWORD
    - secretKey: DB_USER
      remoteRef:
        key: netflow/staging/backend
        property: DB_USER
